### ISSUE TITLE
docker_util.go:L128 slice out of bound

### ISSUE THREAD

**Issue by Laterality** [Laterality/hysteresis#5]
```
ERROR:
Unable to obtain connection from ain copanic: runtime error: slice bounds out of range [12:6]

goroutine 34 [running]:
bufio.(*Reader).fill(0xc0002fe180)
        /usr/local/Cellar/go/1.13.6/libexec/src/bufio/bufio.go:89 +0x202
bufio.(*Reader).WriteTo(0xc0002fe180, 0x7b8300, 0xc0000a6010, 0x7f34f73133e8, 0xc0002fe180, 0x1)
        /usr/local/Cellar/go/1.13.6/libexec/src/bufio/bufio.go:514 +0x106
io.copyBuffer(0x7b8300, 0xc0000a6010, 0x7b7c80, 0xc0002fe180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.13.6/libexec/src/io/io.go:384 +0x33f
io.Copy(0x7b8300, 0xc0000a6010, 0x7b7c80, 0xc0002fe180, 0x0, 0x0, 0x1)
        /usr/local/Cellar/go/1.13.6/libexec/src/io/io.go:364 +0x5a
created by main.AttachContainer
        /Users/sjwoo/projects/latera/hysteresis/docker_util.go:128 +0x12c
```

stderr에 출력되는 경우 io.Copy 호출에서 오류 발생

**Comment by Laterality** [comment]
Fixed by #6
